// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	UnaryDownload(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UnaryDownloadResponse, error)
	StreamDownload(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Service_StreamDownloadClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) UnaryDownload(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UnaryDownloadResponse, error) {
	out := new(UnaryDownloadResponse)
	err := c.cc.Invoke(ctx, "/service.Service/UnaryDownload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) StreamDownload(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Service_StreamDownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], "/service.Service/StreamDownload", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceStreamDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_StreamDownloadClient interface {
	Recv() (*StreamDownloadResponse, error)
	grpc.ClientStream
}

type serviceStreamDownloadClient struct {
	grpc.ClientStream
}

func (x *serviceStreamDownloadClient) Recv() (*StreamDownloadResponse, error) {
	m := new(StreamDownloadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	UnaryDownload(context.Context, *emptypb.Empty) (*UnaryDownloadResponse, error)
	StreamDownload(*emptypb.Empty, Service_StreamDownloadServer) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) UnaryDownload(context.Context, *emptypb.Empty) (*UnaryDownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryDownload not implemented")
}
func (UnimplementedServiceServer) StreamDownload(*emptypb.Empty, Service_StreamDownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamDownload not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_UnaryDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UnaryDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/UnaryDownload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UnaryDownload(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_StreamDownload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).StreamDownload(m, &serviceStreamDownloadServer{stream})
}

type Service_StreamDownloadServer interface {
	Send(*StreamDownloadResponse) error
	grpc.ServerStream
}

type serviceStreamDownloadServer struct {
	grpc.ServerStream
}

func (x *serviceStreamDownloadServer) Send(m *StreamDownloadResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryDownload",
			Handler:    _Service_UnaryDownload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDownload",
			Handler:       _Service_StreamDownload_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}
